# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resources_service_profile import ResourcesServiceProfile  # noqa: F401,E501
from swagger_server.models.one_of_get_service_profiles_response_links_items import OneOfGetServiceProfilesResponseLinksItems  # noqa: F401,E501
from swagger_server import util


class GetServiceProfilesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_profiles: List[ResourcesServiceProfile]=None, links: List[OneOfGetServiceProfilesResponseLinksItems]=None):  # noqa: E501
        """GetServiceProfilesResponse - a model defined in Swagger

        :param service_profiles: The service_profiles of this GetServiceProfilesResponse.  # noqa: E501
        :type service_profiles: List[ResourcesServiceProfile]
        :param links: The links of this GetServiceProfilesResponse.  # noqa: E501
        :type links: List[OneOfGetServiceProfilesResponseLinksItems]
        """
        self.swagger_types = {
            'service_profiles': List[ResourcesServiceProfile],
            'links': List[OneOfGetServiceProfilesResponseLinksItems]
        }

        self.attribute_map = {
            'service_profiles': 'serviceProfiles',
            'links': 'links'
        }
        self._service_profiles = service_profiles
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'GetServiceProfilesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetServiceProfilesResponse of this GetServiceProfilesResponse.  # noqa: E501
        :rtype: GetServiceProfilesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_profiles(self) -> List[ResourcesServiceProfile]:
        """Gets the service_profiles of this GetServiceProfilesResponse.


        :return: The service_profiles of this GetServiceProfilesResponse.
        :rtype: List[ResourcesServiceProfile]
        """
        return self._service_profiles

    @service_profiles.setter
    def service_profiles(self, service_profiles: List[ResourcesServiceProfile]):
        """Sets the service_profiles of this GetServiceProfilesResponse.


        :param service_profiles: The service_profiles of this GetServiceProfilesResponse.
        :type service_profiles: List[ResourcesServiceProfile]
        """

        self._service_profiles = service_profiles

    @property
    def links(self) -> List[OneOfGetServiceProfilesResponseLinksItems]:
        """Gets the links of this GetServiceProfilesResponse.


        :return: The links of this GetServiceProfilesResponse.
        :rtype: List[OneOfGetServiceProfilesResponseLinksItems]
        """
        return self._links

    @links.setter
    def links(self, links: List[OneOfGetServiceProfilesResponseLinksItems]):
        """Sets the links of this GetServiceProfilesResponse.


        :param links: The links of this GetServiceProfilesResponse.
        :type links: List[OneOfGetServiceProfilesResponseLinksItems]
        """

        self._links = links
