# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resources_edge_hosted_service import ResourcesEdgeHostedService  # noqa: F401,E501
from swagger_server.models.one_of_get_service_endpoints_response_links_items import OneOfGetServiceEndpointsResponseLinksItems  # noqa: F401,E501
from swagger_server import util


class GetServiceEndpointsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_endpoints: List[ResourcesEdgeHostedService]=None, links: List[OneOfGetServiceEndpointsResponseLinksItems]=None):  # noqa: E501
        """GetServiceEndpointsResponse - a model defined in Swagger

        :param service_endpoints: The service_endpoints of this GetServiceEndpointsResponse.  # noqa: E501
        :type service_endpoints: List[ResourcesEdgeHostedService]
        :param links: The links of this GetServiceEndpointsResponse.  # noqa: E501
        :type links: List[OneOfGetServiceEndpointsResponseLinksItems]
        """
        self.swagger_types = {
            'service_endpoints': List[ResourcesEdgeHostedService],
            'links': List[OneOfGetServiceEndpointsResponseLinksItems]
        }

        self.attribute_map = {
            'service_endpoints': 'serviceEndpoints',
            'links': 'links'
        }
        self._service_endpoints = service_endpoints
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'GetServiceEndpointsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetServiceEndpointsResponse of this GetServiceEndpointsResponse.  # noqa: E501
        :rtype: GetServiceEndpointsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_endpoints(self) -> List[ResourcesEdgeHostedService]:
        """Gets the service_endpoints of this GetServiceEndpointsResponse.


        :return: The service_endpoints of this GetServiceEndpointsResponse.
        :rtype: List[ResourcesEdgeHostedService]
        """
        return self._service_endpoints

    @service_endpoints.setter
    def service_endpoints(self, service_endpoints: List[ResourcesEdgeHostedService]):
        """Sets the service_endpoints of this GetServiceEndpointsResponse.


        :param service_endpoints: The service_endpoints of this GetServiceEndpointsResponse.
        :type service_endpoints: List[ResourcesEdgeHostedService]
        """

        self._service_endpoints = service_endpoints

    @property
    def links(self) -> List[OneOfGetServiceEndpointsResponseLinksItems]:
        """Gets the links of this GetServiceEndpointsResponse.


        :return: The links of this GetServiceEndpointsResponse.
        :rtype: List[OneOfGetServiceEndpointsResponseLinksItems]
        """
        return self._links

    @links.setter
    def links(self, links: List[OneOfGetServiceEndpointsResponseLinksItems]):
        """Sets the links of this GetServiceEndpointsResponse.


        :param links: The links of this GetServiceEndpointsResponse.
        :type links: List[OneOfGetServiceEndpointsResponseLinksItems]
        """

        self._links = links
