# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_createserviceprofile_link import LinksCreateserviceprofileLink  # noqa: F401,E501
from swagger_server import util


class LinksCreateServiceProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksCreateserviceprofileLink=None):  # noqa: E501
        """LinksCreateServiceProfile - a model defined in Swagger

        :param link: The link of this LinksCreateServiceProfile.  # noqa: E501
        :type link: LinksCreateserviceprofileLink
        """
        self.swagger_types = {
            'link': LinksCreateserviceprofileLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksCreateServiceProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links_Create-service-profile of this LinksCreateServiceProfile.  # noqa: E501
        :rtype: LinksCreateServiceProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksCreateserviceprofileLink:
        """Gets the link of this LinksCreateServiceProfile.


        :return: The link of this LinksCreateServiceProfile.
        :rtype: LinksCreateserviceprofileLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksCreateserviceprofileLink):
        """Sets the link of this LinksCreateServiceProfile.


        :param link: The link of this LinksCreateServiceProfile.
        :type link: LinksCreateserviceprofileLink
        """

        self._link = link
