# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_optimalserviceendpointsbyzone_link import LinksOptimalserviceendpointsbyzoneLink  # noqa: F401,E501
from swagger_server import util


class LinksOptimalServiceEndpointsByZone(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksOptimalserviceendpointsbyzoneLink=None):  # noqa: E501
        """LinksOptimalServiceEndpointsByZone - a model defined in Swagger

        :param link: The link of this LinksOptimalServiceEndpointsByZone.  # noqa: E501
        :type link: LinksOptimalserviceendpointsbyzoneLink
        """
        self.swagger_types = {
            'link': LinksOptimalserviceendpointsbyzoneLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksOptimalServiceEndpointsByZone':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links_Optimal-service-endpoints-by-zone of this LinksOptimalServiceEndpointsByZone.  # noqa: E501
        :rtype: LinksOptimalServiceEndpointsByZone
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksOptimalserviceendpointsbyzoneLink:
        """Gets the link of this LinksOptimalServiceEndpointsByZone.


        :return: The link of this LinksOptimalServiceEndpointsByZone.
        :rtype: LinksOptimalserviceendpointsbyzoneLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksOptimalserviceendpointsbyzoneLink):
        """Sets the link of this LinksOptimalServiceEndpointsByZone.


        :param link: The link of this LinksOptimalServiceEndpointsByZone.
        :type link: LinksOptimalserviceendpointsbyzoneLink
        """

        self._link = link
