# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resources_service_endpoint import ResourcesServiceEndpoint  # noqa: F401,E501
from swagger_server.models.types_edge_resource import TypesEdgeResource  # noqa: F401,E501
from swagger_server.models.types_service_endpoints_id import TypesServiceEndpointsId  # noqa: F401,E501
from swagger_server.models.types_service_profile_id import TypesServiceProfileId  # noqa: F401,E501
from swagger_server import util


class ResourcesEdgeHostedService(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ern: TypesEdgeResource=None, service_endpoints_id: TypesServiceEndpointsId=None, service_endpoint: ResourcesServiceEndpoint=None, application_server_provider_id: str=None, application_id: str=None, service_description: object=None, service_profile_id: TypesServiceProfileId=None):  # noqa: E501
        """ResourcesEdgeHostedService - a model defined in Swagger

        :param ern: The ern of this ResourcesEdgeHostedService.  # noqa: E501
        :type ern: TypesEdgeResource
        :param service_endpoints_id: The service_endpoints_id of this ResourcesEdgeHostedService.  # noqa: E501
        :type service_endpoints_id: TypesServiceEndpointsId
        :param service_endpoint: The service_endpoint of this ResourcesEdgeHostedService.  # noqa: E501
        :type service_endpoint: ResourcesServiceEndpoint
        :param application_server_provider_id: The application_server_provider_id of this ResourcesEdgeHostedService.  # noqa: E501
        :type application_server_provider_id: str
        :param application_id: The application_id of this ResourcesEdgeHostedService.  # noqa: E501
        :type application_id: str
        :param service_description: The service_description of this ResourcesEdgeHostedService.  # noqa: E501
        :type service_description: object
        :param service_profile_id: The service_profile_id of this ResourcesEdgeHostedService.  # noqa: E501
        :type service_profile_id: TypesServiceProfileId
        """
        self.swagger_types = {
            'ern': TypesEdgeResource,
            'service_endpoints_id': TypesServiceEndpointsId,
            'service_endpoint': ResourcesServiceEndpoint,
            'application_server_provider_id': str,
            'application_id': str,
            'service_description': object,
            'service_profile_id': TypesServiceProfileId
        }

        self.attribute_map = {
            'ern': 'ern',
            'service_endpoints_id': 'serviceEndpointsId',
            'service_endpoint': 'serviceEndpoint',
            'application_server_provider_id': 'applicationServerProviderId',
            'application_id': 'applicationId',
            'service_description': 'serviceDescription',
            'service_profile_id': 'serviceProfileID'
        }
        self._ern = ern
        self._service_endpoints_id = service_endpoints_id
        self._service_endpoint = service_endpoint
        self._application_server_provider_id = application_server_provider_id
        self._application_id = application_id
        self._service_description = service_description
        self._service_profile_id = service_profile_id

    @classmethod
    def from_dict(cls, dikt) -> 'ResourcesEdgeHostedService':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The resources_edge_hosted_service of this ResourcesEdgeHostedService.  # noqa: E501
        :rtype: ResourcesEdgeHostedService
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ern(self) -> TypesEdgeResource:
        """Gets the ern of this ResourcesEdgeHostedService.


        :return: The ern of this ResourcesEdgeHostedService.
        :rtype: TypesEdgeResource
        """
        return self._ern

    @ern.setter
    def ern(self, ern: TypesEdgeResource):
        """Sets the ern of this ResourcesEdgeHostedService.


        :param ern: The ern of this ResourcesEdgeHostedService.
        :type ern: TypesEdgeResource
        """

        self._ern = ern

    @property
    def service_endpoints_id(self) -> TypesServiceEndpointsId:
        """Gets the service_endpoints_id of this ResourcesEdgeHostedService.


        :return: The service_endpoints_id of this ResourcesEdgeHostedService.
        :rtype: TypesServiceEndpointsId
        """
        return self._service_endpoints_id

    @service_endpoints_id.setter
    def service_endpoints_id(self, service_endpoints_id: TypesServiceEndpointsId):
        """Sets the service_endpoints_id of this ResourcesEdgeHostedService.


        :param service_endpoints_id: The service_endpoints_id of this ResourcesEdgeHostedService.
        :type service_endpoints_id: TypesServiceEndpointsId
        """

        self._service_endpoints_id = service_endpoints_id

    @property
    def service_endpoint(self) -> ResourcesServiceEndpoint:
        """Gets the service_endpoint of this ResourcesEdgeHostedService.


        :return: The service_endpoint of this ResourcesEdgeHostedService.
        :rtype: ResourcesServiceEndpoint
        """
        return self._service_endpoint

    @service_endpoint.setter
    def service_endpoint(self, service_endpoint: ResourcesServiceEndpoint):
        """Sets the service_endpoint of this ResourcesEdgeHostedService.


        :param service_endpoint: The service_endpoint of this ResourcesEdgeHostedService.
        :type service_endpoint: ResourcesServiceEndpoint
        """

        self._service_endpoint = service_endpoint

    @property
    def application_server_provider_id(self) -> str:
        """Gets the application_server_provider_id of this ResourcesEdgeHostedService.

        Unique ID representing the Edge Application Provider  # noqa: E501

        :return: The application_server_provider_id of this ResourcesEdgeHostedService.
        :rtype: str
        """
        return self._application_server_provider_id

    @application_server_provider_id.setter
    def application_server_provider_id(self, application_server_provider_id: str):
        """Sets the application_server_provider_id of this ResourcesEdgeHostedService.

        Unique ID representing the Edge Application Provider  # noqa: E501

        :param application_server_provider_id: The application_server_provider_id of this ResourcesEdgeHostedService.
        :type application_server_provider_id: str
        """

        self._application_server_provider_id = application_server_provider_id

    @property
    def application_id(self) -> str:
        """Gets the application_id of this ResourcesEdgeHostedService.

        Unique ID representing the Edge Application  # noqa: E501

        :return: The application_id of this ResourcesEdgeHostedService.
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id: str):
        """Sets the application_id of this ResourcesEdgeHostedService.

        Unique ID representing the Edge Application  # noqa: E501

        :param application_id: The application_id of this ResourcesEdgeHostedService.
        :type application_id: str
        """

        self._application_id = application_id

    @property
    def service_description(self) -> object:
        """Gets the service_description of this ResourcesEdgeHostedService.

        Description of the Service Endpoint  # noqa: E501

        :return: The service_description of this ResourcesEdgeHostedService.
        :rtype: object
        """
        return self._service_description

    @service_description.setter
    def service_description(self, service_description: object):
        """Sets the service_description of this ResourcesEdgeHostedService.

        Description of the Service Endpoint  # noqa: E501

        :param service_description: The service_description of this ResourcesEdgeHostedService.
        :type service_description: object
        """

        self._service_description = service_description

    @property
    def service_profile_id(self) -> TypesServiceProfileId:
        """Gets the service_profile_id of this ResourcesEdgeHostedService.


        :return: The service_profile_id of this ResourcesEdgeHostedService.
        :rtype: TypesServiceProfileId
        """
        return self._service_profile_id

    @service_profile_id.setter
    def service_profile_id(self, service_profile_id: TypesServiceProfileId):
        """Sets the service_profile_id of this ResourcesEdgeHostedService.


        :param service_profile_id: The service_profile_id of this ResourcesEdgeHostedService.
        :type service_profile_id: TypesServiceProfileId
        """

        self._service_profile_id = service_profile_id
