# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resources_edge_hosted_service import ResourcesEdgeHostedService  # noqa: F401,E501
from swagger_server import util


class ResourcesEdgeServiceDescription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, edge_hosted_service: ResourcesEdgeHostedService=None):  # noqa: E501
        """ResourcesEdgeServiceDescription - a model defined in Swagger

        :param edge_hosted_service: The edge_hosted_service of this ResourcesEdgeServiceDescription.  # noqa: E501
        :type edge_hosted_service: ResourcesEdgeHostedService
        """
        self.swagger_types = {
            'edge_hosted_service': ResourcesEdgeHostedService
        }

        self.attribute_map = {
            'edge_hosted_service': 'edgeHostedService'
        }
        self._edge_hosted_service = edge_hosted_service

    @classmethod
    def from_dict(cls, dikt) -> 'ResourcesEdgeServiceDescription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The resources_edge_service_description of this ResourcesEdgeServiceDescription.  # noqa: E501
        :rtype: ResourcesEdgeServiceDescription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edge_hosted_service(self) -> ResourcesEdgeHostedService:
        """Gets the edge_hosted_service of this ResourcesEdgeServiceDescription.


        :return: The edge_hosted_service of this ResourcesEdgeServiceDescription.
        :rtype: ResourcesEdgeHostedService
        """
        return self._edge_hosted_service

    @edge_hosted_service.setter
    def edge_hosted_service(self, edge_hosted_service: ResourcesEdgeHostedService):
        """Sets the edge_hosted_service of this ResourcesEdgeServiceDescription.


        :param edge_hosted_service: The edge_hosted_service of this ResourcesEdgeServiceDescription.
        :type edge_hosted_service: ResourcesEdgeHostedService
        """

        self._edge_hosted_service = edge_hosted_service
