# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_self_link import LinksSelfLink  # noqa: F401,E501
from swagger_server import util


class LinksSelf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksSelfLink=None):  # noqa: E501
        """LinksSelf - a model defined in Swagger

        :param link: The link of this LinksSelf.  # noqa: E501
        :type link: LinksSelfLink
        """
        self.swagger_types = {
            'link': LinksSelfLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksSelf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The linksSelf of this LinksSelf.  # noqa: E501
        :rtype: LinksSelf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksSelfLink:
        """Gets the link of this LinksSelf.


        :return: The link of this LinksSelf.
        :rtype: LinksSelfLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksSelfLink):
        """Sets the link of this LinksSelf.


        :param link: The link of this LinksSelf.
        :type link: LinksSelfLink
        """

        self._link = link
