# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resources_region_metadata import ResourcesRegionMetadata  # noqa: F401,E501
from swagger_server.models.one_of_get_regions_response_links_items import OneOfGetRegionsResponseLinksItems  # noqa: F401,E501
from swagger_server import util


class GetRegionsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, regions: List[ResourcesRegionMetadata]=None, links: List[OneOfGetRegionsResponseLinksItems]=None):  # noqa: E501
        """GetRegionsResponse - a model defined in Swagger

        :param regions: The regions of this GetRegionsResponse.  # noqa: E501
        :type regions: List[ResourcesRegionMetadata]
        :param links: The links of this GetRegionsResponse.  # noqa: E501
        :type links: List[OneOfGetRegionsResponseLinksItems]
        """
        self.swagger_types = {
            'regions': List[ResourcesRegionMetadata],
            'links': List[OneOfGetRegionsResponseLinksItems]
        }

        self.attribute_map = {
            'regions': 'regions',
            'links': 'links'
        }
        self._regions = regions
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'GetRegionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetRegionsResponse of this GetRegionsResponse.  # noqa: E501
        :rtype: GetRegionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def regions(self) -> List[ResourcesRegionMetadata]:
        """Gets the regions of this GetRegionsResponse.


        :return: The regions of this GetRegionsResponse.
        :rtype: List[ResourcesRegionMetadata]
        """
        return self._regions

    @regions.setter
    def regions(self, regions: List[ResourcesRegionMetadata]):
        """Sets the regions of this GetRegionsResponse.


        :param regions: The regions of this GetRegionsResponse.
        :type regions: List[ResourcesRegionMetadata]
        """

        self._regions = regions

    @property
    def links(self) -> List[OneOfGetRegionsResponseLinksItems]:
        """Gets the links of this GetRegionsResponse.


        :return: The links of this GetRegionsResponse.
        :rtype: List[OneOfGetRegionsResponseLinksItems]
        """
        return self._links

    @links.setter
    def links(self, links: List[OneOfGetRegionsResponseLinksItems]):
        """Sets the links of this GetRegionsResponse.


        :param links: The links of this GetRegionsResponse.
        :type links: List[OneOfGetRegionsResponseLinksItems]
        """

        self._links = links
