# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_deleteserviceprofile_link import LinksDeleteserviceprofileLink  # noqa: F401,E501
from swagger_server import util


class LinksDeleteServiceProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksDeleteserviceprofileLink=None):  # noqa: E501
        """LinksDeleteServiceProfile - a model defined in Swagger

        :param link: The link of this LinksDeleteServiceProfile.  # noqa: E501
        :type link: LinksDeleteserviceprofileLink
        """
        self.swagger_types = {
            'link': LinksDeleteserviceprofileLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksDeleteServiceProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links_Delete-service-profile of this LinksDeleteServiceProfile.  # noqa: E501
        :rtype: LinksDeleteServiceProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksDeleteserviceprofileLink:
        """Gets the link of this LinksDeleteServiceProfile.


        :return: The link of this LinksDeleteServiceProfile.
        :rtype: LinksDeleteserviceprofileLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksDeleteserviceprofileLink):
        """Sets the link of this LinksDeleteServiceProfile.


        :param link: The link of this LinksDeleteServiceProfile.
        :type link: LinksDeleteserviceprofileLink
        """

        self._link = link
