# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_optimal_me_cplatformsbyregion_link import LinksOptimalMECplatformsbyregionLink  # noqa: F401,E501
from swagger_server import util


class LinksOptimalMECPlatformsByRegion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksOptimalMECplatformsbyregionLink=None):  # noqa: E501
        """LinksOptimalMECPlatformsByRegion - a model defined in Swagger

        :param link: The link of this LinksOptimalMECPlatformsByRegion.  # noqa: E501
        :type link: LinksOptimalMECplatformsbyregionLink
        """
        self.swagger_types = {
            'link': LinksOptimalMECplatformsbyregionLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksOptimalMECPlatformsByRegion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links_Optimal-MEC-platforms-by-region of this LinksOptimalMECPlatformsByRegion.  # noqa: E501
        :rtype: LinksOptimalMECPlatformsByRegion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksOptimalMECplatformsbyregionLink:
        """Gets the link of this LinksOptimalMECPlatformsByRegion.


        :return: The link of this LinksOptimalMECPlatformsByRegion.
        :rtype: LinksOptimalMECplatformsbyregionLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksOptimalMECplatformsbyregionLink):
        """Sets the link of this LinksOptimalMECPlatformsByRegion.


        :param link: The link of this LinksOptimalMECPlatformsByRegion.
        :type link: LinksOptimalMECplatformsbyregionLink
        """

        self._link = link
