# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_termsof_service_link import LinksTermsofServiceLink  # noqa: F401,E501
from swagger_server import util


class LinksTermsOfService(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksTermsofServiceLink=None):  # noqa: E501
        """LinksTermsOfService - a model defined in Swagger

        :param link: The link of this LinksTermsOfService.  # noqa: E501
        :type link: LinksTermsofServiceLink
        """
        self.swagger_types = {
            'link': LinksTermsofServiceLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksTermsOfService':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links_Terms-of-Service of this LinksTermsOfService.  # noqa: E501
        :rtype: LinksTermsOfService
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksTermsofServiceLink:
        """Gets the link of this LinksTermsOfService.


        :return: The link of this LinksTermsOfService.
        :rtype: LinksTermsofServiceLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksTermsofServiceLink):
        """Sets the link of this LinksTermsOfService.


        :param link: The link of this LinksTermsOfService.
        :type link: LinksTermsofServiceLink
        """

        self._link = link
