# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_all_service_endpoints_link import LinksAllServiceEndpointsLink  # noqa: F401,E501
from swagger_server import util


class LinksAllServiceEndpoints(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksAllServiceEndpointsLink=None):  # noqa: E501
        """LinksAllServiceEndpoints - a model defined in Swagger

        :param link: The link of this LinksAllServiceEndpoints.  # noqa: E501
        :type link: LinksAllServiceEndpointsLink
        """
        self.swagger_types = {
            'link': LinksAllServiceEndpointsLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksAllServiceEndpoints':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksAllServiceEndpoints of this LinksAllServiceEndpoints.  # noqa: E501
        :rtype: LinksAllServiceEndpoints
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksAllServiceEndpointsLink:
        """Gets the link of this LinksAllServiceEndpoints.


        :return: The link of this LinksAllServiceEndpoints.
        :rtype: LinksAllServiceEndpointsLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksAllServiceEndpointsLink):
        """Sets the link of this LinksAllServiceEndpoints.


        :param link: The link of this LinksAllServiceEndpoints.
        :type link: LinksAllServiceEndpointsLink
        """

        self._link = link
