# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_bookmark_link import LinksBookmarkLink  # noqa: F401,E501
from swagger_server import util


class LinksBookmark(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksBookmarkLink=None):  # noqa: E501
        """LinksBookmark - a model defined in Swagger

        :param link: The link of this LinksBookmark.  # noqa: E501
        :type link: LinksBookmarkLink
        """
        self.swagger_types = {
            'link': LinksBookmarkLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksBookmark':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksBookmark of this LinksBookmark.  # noqa: E501
        :rtype: LinksBookmark
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksBookmarkLink:
        """Gets the link of this LinksBookmark.


        :return: The link of this LinksBookmark.
        :rtype: LinksBookmarkLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksBookmarkLink):
        """Sets the link of this LinksBookmark.


        :param link: The link of this LinksBookmark.
        :type link: LinksBookmarkLink
        """

        self._link = link
