# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_optimal_mec_platforms_by_zone_link import LinksOptimalMECPlatformsByZoneLink  # noqa: F401,E501
from swagger_server import util


class LinksOptimalMECPlatformsByZone(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksOptimalMECPlatformsByZoneLink=None):  # noqa: E501
        """LinksOptimalMECPlatformsByZone - a model defined in Swagger

        :param link: The link of this LinksOptimalMECPlatformsByZone.  # noqa: E501
        :type link: LinksOptimalMECPlatformsByZoneLink
        """
        self.swagger_types = {
            'link': LinksOptimalMECPlatformsByZoneLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksOptimalMECPlatformsByZone':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksOptimalMECPlatformsByZone of this LinksOptimalMECPlatformsByZone.  # noqa: E501
        :rtype: LinksOptimalMECPlatformsByZone
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksOptimalMECPlatformsByZoneLink:
        """Gets the link of this LinksOptimalMECPlatformsByZone.


        :return: The link of this LinksOptimalMECPlatformsByZone.
        :rtype: LinksOptimalMECPlatformsByZoneLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksOptimalMECPlatformsByZoneLink):
        """Sets the link of this LinksOptimalMECPlatformsByZone.


        :param link: The link of this LinksOptimalMECPlatformsByZone.
        :type link: LinksOptimalMECPlatformsByZoneLink
        """

        self._link = link
