# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_all_service_profiles_link import LinksAllServiceProfilesLink  # noqa: F401,E501
from swagger_server import util


class LinksAllServiceProfiles(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksAllServiceProfilesLink=None):  # noqa: E501
        """LinksAllServiceProfiles - a model defined in Swagger

        :param link: The link of this LinksAllServiceProfiles.  # noqa: E501
        :type link: LinksAllServiceProfilesLink
        """
        self.swagger_types = {
            'link': LinksAllServiceProfilesLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksAllServiceProfiles':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksAllServiceProfiles of this LinksAllServiceProfiles.  # noqa: E501
        :rtype: LinksAllServiceProfiles
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksAllServiceProfilesLink:
        """Gets the link of this LinksAllServiceProfiles.


        :return: The link of this LinksAllServiceProfiles.
        :rtype: LinksAllServiceProfilesLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksAllServiceProfilesLink):
        """Sets the link of this LinksAllServiceProfiles.


        :param link: The link of this LinksAllServiceProfiles.
        :type link: LinksAllServiceProfilesLink
        """

        self._link = link
