# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_delete_service_endpoint_link import LinksDeleteServiceEndpointLink  # noqa: F401,E501
from swagger_server import util


class LinksDeleteServiceEndpoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksDeleteServiceEndpointLink=None):  # noqa: E501
        """LinksDeleteServiceEndpoint - a model defined in Swagger

        :param link: The link of this LinksDeleteServiceEndpoint.  # noqa: E501
        :type link: LinksDeleteServiceEndpointLink
        """
        self.swagger_types = {
            'link': LinksDeleteServiceEndpointLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksDeleteServiceEndpoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksDeleteServiceEndpoint of this LinksDeleteServiceEndpoint.  # noqa: E501
        :rtype: LinksDeleteServiceEndpoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksDeleteServiceEndpointLink:
        """Gets the link of this LinksDeleteServiceEndpoint.


        :return: The link of this LinksDeleteServiceEndpoint.
        :rtype: LinksDeleteServiceEndpointLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksDeleteServiceEndpointLink):
        """Sets the link of this LinksDeleteServiceEndpoint.


        :param link: The link of this LinksDeleteServiceEndpoint.
        :type link: LinksDeleteServiceEndpointLink
        """

        self._link = link
