# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_delete_service_profile_link import LinksDeleteServiceProfileLink  # noqa: F401,E501
from swagger_server import util


class LinksDeleteServiceProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksDeleteServiceProfileLink=None):  # noqa: E501
        """LinksDeleteServiceProfile - a model defined in Swagger

        :param link: The link of this LinksDeleteServiceProfile.  # noqa: E501
        :type link: LinksDeleteServiceProfileLink
        """
        self.swagger_types = {
            'link': LinksDeleteServiceProfileLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksDeleteServiceProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksDeleteServiceProfile of this LinksDeleteServiceProfile.  # noqa: E501
        :rtype: LinksDeleteServiceProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksDeleteServiceProfileLink:
        """Gets the link of this LinksDeleteServiceProfile.


        :return: The link of this LinksDeleteServiceProfile.
        :rtype: LinksDeleteServiceProfileLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksDeleteServiceProfileLink):
        """Sets the link of this LinksDeleteServiceProfile.


        :param link: The link of this LinksDeleteServiceProfile.
        :type link: LinksDeleteServiceProfileLink
        """

        self._link = link
