# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_update_service_profile_link import LinksUpdateServiceProfileLink  # noqa: F401,E501
from swagger_server import util


class LinksUpdateServiceProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksUpdateServiceProfileLink=None):  # noqa: E501
        """LinksUpdateServiceProfile - a model defined in Swagger

        :param link: The link of this LinksUpdateServiceProfile.  # noqa: E501
        :type link: LinksUpdateServiceProfileLink
        """
        self.swagger_types = {
            'link': LinksUpdateServiceProfileLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksUpdateServiceProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksUpdateServiceProfile of this LinksUpdateServiceProfile.  # noqa: E501
        :rtype: LinksUpdateServiceProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksUpdateServiceProfileLink:
        """Gets the link of this LinksUpdateServiceProfile.


        :return: The link of this LinksUpdateServiceProfile.
        :rtype: LinksUpdateServiceProfileLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksUpdateServiceProfileLink):
        """Sets the link of this LinksUpdateServiceProfile.


        :param link: The link of this LinksUpdateServiceProfile.
        :type link: LinksUpdateServiceProfileLink
        """

        self._link = link
