# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_all_mec_platforms_link import LinksAllMecPlatformsLink  # noqa: F401,E501
from swagger_server import util


class LinksAllMecPlatforms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksAllMecPlatformsLink=None):  # noqa: E501
        """LinksAllMecPlatforms - a model defined in Swagger

        :param link: The link of this LinksAllMecPlatforms.  # noqa: E501
        :type link: LinksAllMecPlatformsLink
        """
        self.swagger_types = {
            'link': LinksAllMecPlatformsLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksAllMecPlatforms':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinksAllMecPlatforms of this LinksAllMecPlatforms.  # noqa: E501
        :rtype: LinksAllMecPlatforms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksAllMecPlatformsLink:
        """Gets the link of this LinksAllMecPlatforms.


        :return: The link of this LinksAllMecPlatforms.
        :rtype: LinksAllMecPlatformsLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksAllMecPlatformsLink):
        """Sets the link of this LinksAllMecPlatforms.


        :param link: The link of this LinksAllMecPlatforms.
        :type link: LinksAllMecPlatformsLink
        """

        self._link = link
