# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_common import LinksCommon  # noqa: F401,E501
from swagger_server import util


class TypesError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None, message: str=None, links: LinksCommon=None):  # noqa: E501
        """TypesError - a model defined in Swagger

        :param code: The code of this TypesError.  # noqa: E501
        :type code: str
        :param message: The message of this TypesError.  # noqa: E501
        :type message: str
        :param links: The links of this TypesError.  # noqa: E501
        :type links: LinksCommon
        """
        self.swagger_types = {
            'code': str,
            'message': str,
            'links': LinksCommon
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'links': 'links'
        }
        self._code = code
        self._message = message
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'TypesError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TypesError of this TypesError.  # noqa: E501
        :rtype: TypesError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this TypesError.


        :return: The code of this TypesError.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this TypesError.


        :param code: The code of this TypesError.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this TypesError.


        :return: The message of this TypesError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this TypesError.


        :param message: The message of this TypesError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def links(self) -> LinksCommon:
        """Gets the links of this TypesError.


        :return: The links of this TypesError.
        :rtype: LinksCommon
        """
        return self._links

    @links.setter
    def links(self, links: LinksCommon):
        """Sets the links of this TypesError.


        :param links: The links of this TypesError.
        :type links: LinksCommon
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links
