# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_optimalserviceendpointsbyserviceprofile_link import LinksOptimalserviceendpointsbyserviceprofileLink  # noqa: F401,E501
from swagger_server import util


class LinksOptimalServiceEndpointsByServiceProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: LinksOptimalserviceendpointsbyserviceprofileLink=None):  # noqa: E501
        """LinksOptimalServiceEndpointsByServiceProfile - a model defined in Swagger

        :param link: The link of this LinksOptimalServiceEndpointsByServiceProfile.  # noqa: E501
        :type link: LinksOptimalserviceendpointsbyserviceprofileLink
        """
        self.swagger_types = {
            'link': LinksOptimalserviceendpointsbyserviceprofileLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'LinksOptimalServiceEndpointsByServiceProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links_Optimal-service-endpoints-by-service-profile of this LinksOptimalServiceEndpointsByServiceProfile.  # noqa: E501
        :rtype: LinksOptimalServiceEndpointsByServiceProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> LinksOptimalserviceendpointsbyserviceprofileLink:
        """Gets the link of this LinksOptimalServiceEndpointsByServiceProfile.


        :return: The link of this LinksOptimalServiceEndpointsByServiceProfile.
        :rtype: LinksOptimalserviceendpointsbyserviceprofileLink
        """
        return self._link

    @link.setter
    def link(self, link: LinksOptimalserviceendpointsbyserviceprofileLink):
        """Sets the link of this LinksOptimalServiceEndpointsByServiceProfile.


        :param link: The link of this LinksOptimalServiceEndpointsByServiceProfile.
        :type link: LinksOptimalserviceendpointsbyserviceprofileLink
        """

        self._link = link
