# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.types_service_endpoints_id import TypesServiceEndpointsId  # noqa: F401,E501
from swagger_server.models.one_of_post_service_endpoint_response_links_items import OneOfPostServiceEndpointResponseLinksItems  # noqa: F401,E501
from swagger_server import util


class PostServiceEndpointResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_endpoints_id: TypesServiceEndpointsId=None, links: List[OneOfPostServiceEndpointResponseLinksItems]=None):  # noqa: E501
        """PostServiceEndpointResponse - a model defined in Swagger

        :param service_endpoints_id: The service_endpoints_id of this PostServiceEndpointResponse.  # noqa: E501
        :type service_endpoints_id: TypesServiceEndpointsId
        :param links: The links of this PostServiceEndpointResponse.  # noqa: E501
        :type links: List[OneOfPostServiceEndpointResponseLinksItems]
        """
        self.swagger_types = {
            'service_endpoints_id': TypesServiceEndpointsId,
            'links': List[OneOfPostServiceEndpointResponseLinksItems]
        }

        self.attribute_map = {
            'service_endpoints_id': 'serviceEndpointsId',
            'links': 'links'
        }
        self._service_endpoints_id = service_endpoints_id
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'PostServiceEndpointResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostServiceEndpointResponse of this PostServiceEndpointResponse.  # noqa: E501
        :rtype: PostServiceEndpointResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_endpoints_id(self) -> TypesServiceEndpointsId:
        """Gets the service_endpoints_id of this PostServiceEndpointResponse.


        :return: The service_endpoints_id of this PostServiceEndpointResponse.
        :rtype: TypesServiceEndpointsId
        """
        return self._service_endpoints_id

    @service_endpoints_id.setter
    def service_endpoints_id(self, service_endpoints_id: TypesServiceEndpointsId):
        """Sets the service_endpoints_id of this PostServiceEndpointResponse.


        :param service_endpoints_id: The service_endpoints_id of this PostServiceEndpointResponse.
        :type service_endpoints_id: TypesServiceEndpointsId
        """

        self._service_endpoints_id = service_endpoints_id

    @property
    def links(self) -> List[OneOfPostServiceEndpointResponseLinksItems]:
        """Gets the links of this PostServiceEndpointResponse.


        :return: The links of this PostServiceEndpointResponse.
        :rtype: List[OneOfPostServiceEndpointResponseLinksItems]
        """
        return self._links

    @links.setter
    def links(self, links: List[OneOfPostServiceEndpointResponseLinksItems]):
        """Sets the links of this PostServiceEndpointResponse.


        :param links: The links of this PostServiceEndpointResponse.
        :type links: List[OneOfPostServiceEndpointResponseLinksItems]
        """

        self._links = links
