# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.types_service_profile_id import TypesServiceProfileId  # noqa: F401,E501
from swagger_server.models.one_of_post_service_profile_response_links_items import OneOfPostServiceProfileResponseLinksItems  # noqa: F401,E501
from swagger_server import util


class PostServiceProfileResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_profile_id: TypesServiceProfileId=None, links: List[OneOfPostServiceProfileResponseLinksItems]=None):  # noqa: E501
        """PostServiceProfileResponse - a model defined in Swagger

        :param service_profile_id: The service_profile_id of this PostServiceProfileResponse.  # noqa: E501
        :type service_profile_id: TypesServiceProfileId
        :param links: The links of this PostServiceProfileResponse.  # noqa: E501
        :type links: List[OneOfPostServiceProfileResponseLinksItems]
        """
        self.swagger_types = {
            'service_profile_id': TypesServiceProfileId,
            'links': List[OneOfPostServiceProfileResponseLinksItems]
        }

        self.attribute_map = {
            'service_profile_id': 'serviceProfileId',
            'links': 'links'
        }
        self._service_profile_id = service_profile_id
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'PostServiceProfileResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostServiceProfileResponse of this PostServiceProfileResponse.  # noqa: E501
        :rtype: PostServiceProfileResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_profile_id(self) -> TypesServiceProfileId:
        """Gets the service_profile_id of this PostServiceProfileResponse.


        :return: The service_profile_id of this PostServiceProfileResponse.
        :rtype: TypesServiceProfileId
        """
        return self._service_profile_id

    @service_profile_id.setter
    def service_profile_id(self, service_profile_id: TypesServiceProfileId):
        """Sets the service_profile_id of this PostServiceProfileResponse.


        :param service_profile_id: The service_profile_id of this PostServiceProfileResponse.
        :type service_profile_id: TypesServiceProfileId
        """

        self._service_profile_id = service_profile_id

    @property
    def links(self) -> List[OneOfPostServiceProfileResponseLinksItems]:
        """Gets the links of this PostServiceProfileResponse.


        :return: The links of this PostServiceProfileResponse.
        :rtype: List[OneOfPostServiceProfileResponseLinksItems]
        """
        return self._links

    @links.setter
    def links(self, links: List[OneOfPostServiceProfileResponseLinksItems]):
        """Sets the links of this PostServiceProfileResponse.


        :param links: The links of this PostServiceProfileResponse.
        :type links: List[OneOfPostServiceProfileResponseLinksItems]
        """

        self._links = links
